spring:
  application:
    name: CodeJourney-CoLab-Backend
  datasource:
    url: jdbc:mysql://localhost:3306/Code_Journey_CoLab?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    # *改成你自己的本地数据库用户名和密码！
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret: codejourneycolab#secret*key-wohenshenmiwohenshenmi
  expiration: 604800000

server:
  port: 8048

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.tongji.codejourneycolab.codejourneycolabbackend.entity
